/**
 * Adjective deck: Tatoeba sentences with an adjective cut out. The gap shows
 * its dictionary form as a hint («stor»), and the learner picks or types the
 * form the sentence needs («stort»).
 *
 * `tatoeba.json` is generated by `pnpm run data`; `overrides.json` adds
 * reviewed alternatives, AI translations, corrected tags, explanations and
 * exclusions on top, since the generated file is overwritten.
 */
import type { Deck } from '../../core/types.ts';
import { reviewedTatoebaLoader } from '../tatoeba-source.ts';

const DECK_ID = 'adjectives';

const loadReviewedTatoeba = reviewedTatoebaLoader(
  { deckId: DECK_ID, idPrefix: 'a-' },
  // Dynamic import keeps the corpus out of the initial bundle.
  async () => (await import('./tatoeba.json')).default,
  async () => (await import('./overrides.json')).default,
);

export const adjectiveDeck: Deck = {
  id: DECK_ID,
  title: 'Adjektivbøying',
  shortTitle: 'Adjektiver',
  description: 'stor, stort, store … Bøy adjektivet riktig.',
  icon: '🎨',
  tagLabel: 'Form',
  sources: [{ dataKind: 'cloze', tasks: ['multiple-choice', 'type-in'], load: loadReviewedTatoeba }],
};
