/**
 * Word-order deck: Tatoeba sentences cut into word tiles. The learner sees the
 * German or English translation and puts the Norwegian words in order —
 * verb second, inversion after a fronted adverbial, «ikke» before the verb in
 * subordinate clauses.
 *
 * `tatoeba.json` is generated by `pnpm run data`; `overrides.json` adds the
 * reviewed rule, explanation, other correct orders, AI translations and
 * exclusions on top, since the generated file is overwritten.
 */
import type { Deck } from '../../core/types.ts';
import { reviewedTatoebaLoader } from '../tatoeba-source.ts';

const DECK_ID = 'word-order';

const loadReviewedTatoeba = reviewedTatoebaLoader(
  { deckId: DECK_ID, idPrefix: 'w-' },
  // Dynamic import keeps the corpus out of the initial bundle.
  async () => (await import('./tatoeba.json')).default,
  async () => (await import('./overrides.json')).default,
);

export const wordOrderDeck: Deck = {
  id: DECK_ID,
  title: 'Ordstilling',
  shortTitle: 'Ordstilling',
  description: 'Verbet på plass nummer to, inversjon, leddsetninger … Sett ordene i riktig rekkefølge.',
  icon: '🧩',
  tagLabel: 'Regel',
  sources: [{ dataKind: 'sentence', tasks: ['word-order'], load: loadReviewedTatoeba }],
};
