/**
 * Hand-written preposition exercises.
 *
 * These carry an explanation and are the backbone of the deck: the corpus
 * items drill recognition, these teach the rule. Keep explanations short and
 * concrete — they are shown right after answering.
 *
 * Every distractor must be clearly wrong in its sentence. Antonyms and
 * near-synonyms that also fit («før/etter jobb», «ved/på sykehuset») do not
 * belong in `options`. `content.test.ts` enforces the mechanical part.
 */
import type { Exercise, Level } from '../../core/types.ts';
import type { Preposition } from './prepositions.ts';
import type { Topic } from './topics.ts';

interface CuratedItem {
  /** Stable key for SRS history. Never change or reuse it once shipped. */
  readonly id: string;
  readonly prompt: string;
  readonly answer: Preposition;
  readonly options: readonly Preposition[];
  readonly explanation: string;
  readonly topic: Topic;
  readonly level: Level;
  readonly de?: string;
  /**
   * Distractors from `EXCLUDED_DISTRACTORS` that this sentence's context
   * rules out on its own («når vi kommer hjem» leaves no room for «før»).
   * Without this opt-out such a pair fails the content test.
   */
  readonly allowedContrasts?: readonly Preposition[];
}

const ITEMS: readonly CuratedItem[] = [
  // --- Sted: i / på / hos / ved ---------------------------------------------
  {
    id: 'sted-bor-norge',
    prompt: 'Jeg bor ___ Norge.',
    answer: 'i',
    options: ['i', 'på', 'til', 'hos'],
    explanation: 'Land og byer tar «i»: Jeg bor i Norge, i Oslo.',
    topic: 'sted',
    level: 1,
    de: 'Ich wohne in Norwegen.',
  },
  {
    id: 'sted-studerer-universitetet',
    prompt: 'Hun studerer ___ universitetet i Oslo.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation:
      'Institusjoner tar oftest «på»: på universitetet, på sykehuset, på skolen. Formelt sier man også «ved universitetet».',
    topic: 'sted',
    level: 1,
    de: 'Sie studiert an der Universität Oslo.',
  },
  {
    id: 'sted-bok-bordet',
    prompt: 'Boka ligger ___ bordet.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation: 'Oppå en flate: «på». «I bordet» ville betydd inni treverket.',
    topic: 'sted',
    level: 1,
    de: 'Das Buch liegt auf dem Tisch.',
  },
  {
    id: 'sted-melk-kjoleskapet',
    prompt: 'Melka må stå ___ kjøleskapet, ellers blir den sur.',
    answer: 'i',
    options: ['i', 'på', 'ved', 'hos'],
    explanation: 'Inni et lukket rom: «i». «På kjøleskapet» = oppå det, og der blir melka sur.',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-lunsj-kafe',
    prompt: 'Vi spiste lunsj ___ kafé i går.',
    answer: 'på',
    options: ['på', 'i', 'ved', 'hos'],
    explanation: 'Offentlige steder man oppsøker: på kafé, på kino, på restaurant.',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-hos-legen',
    prompt: 'Jeg var ___ legen i går.',
    answer: 'hos',
    options: ['hos', 'ved', 'i', 'mot'],
    explanation: '«Hos» + person: hos legen, hos tannlegen, hos bestemor. Tysk «beim Arzt» blir ikke «ved».',
    topic: 'sted',
    level: 2,
    de: 'Ich war gestern beim Arzt.',
  },
  {
    id: 'sted-huset-sjoen',
    prompt: 'Huset ligger ___ sjøen.',
    answer: 'ved',
    options: ['ved', 'på', 'i', 'til'],
    explanation: '«Ved» = like inntil, i nærheten av: ved sjøen, ved vinduet, ved døra.',
    topic: 'sted',
    level: 2,
  },
  {
    id: 'sted-bilen-bak-huset',
    prompt: 'Bilen står ___ huset, så du ser den ikke fra gata.',
    answer: 'bak',
    options: ['bak', 'foran', 'over', 'mellom'],
    explanation: '«Bak» = på baksiden av. Stod bilen «foran» huset, ville du sett den fra gata.',
    topic: 'sted',
    level: 2,
    allowedContrasts: ['foran'],
  },
  {
    id: 'sted-mellom-banken-apoteket',
    prompt: 'Butikken ligger ___ banken og apoteket.',
    answer: 'mellom',
    options: ['mellom', 'blant', 'hos', 'gjennom'],
    explanation: '«Mellom» med to størrelser, «blant» med en gruppe på flere.',
    topic: 'sted',
    level: 2,
  },
  {
    id: 'sted-blant-gjestene',
    prompt: 'Hun var den eneste nordmannen ___ gjestene.',
    answer: 'blant',
    options: ['blant', 'i', 'hos', 'ved'],
    explanation: 'En gruppe på flere enn to: «blant». Med nøyaktig to: «mellom».',
    topic: 'sted',
    level: 3,
  },
  {
    id: 'sted-bildet-veggen',
    prompt: 'Bildet henger ___ veggen i stua.',
    answer: 'på',
    options: ['på', 'i', 'til', 'av'],
    explanation: 'Ting som henger på en loddrett flate, tar også «på»: på veggen, på døra.',
    topic: 'sted',
    level: 1,
    de: 'Das Bild hängt an der Wand im Wohnzimmer.',
  },
  {
    id: 'sted-leker-hagen',
    prompt: 'Barna leker ute ___ hagen.',
    answer: 'i',
    options: ['i', 'på', 'til', 'hos'],
    explanation: 'Et område med gjerde eller grenser rundt tar «i»: i hagen, i parken.',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-kjokkenet',
    prompt: 'Pappa lager middag ___ kjøkkenet.',
    answer: 'på',
    options: ['på', 'til', 'hos', 'av'],
    explanation: 'Mange rom i huset tar «på»: på kjøkkenet, på badet, på soverommet. Stua tar oftest «i».',
    topic: 'sted',
    level: 2,
    de: 'Papa kocht in der Küche Abendessen.',
  },
  {
    id: 'sted-time-hos-frisoren',
    prompt: 'Jeg har time ___ frisøren i morgen.',
    answer: 'hos',
    options: ['hos', 'ved', 'i', 'mot'],
    explanation: '«Time hos» + fagperson: hos frisøren, hos legen, hos tannlegen.',
    topic: 'sted',
    level: 2,
    de: 'Ich habe morgen einen Termin beim Friseur.',
  },
  {
    id: 'sted-overnatter-hos',
    prompt: 'Barna overnatter ___ besteforeldrene i helgen.',
    answer: 'hos',
    options: ['hos', 'ved', 'på', 'mot'],
    explanation: 'Hjemme hos noen: «hos». Tysk «bei den Großeltern» blir ikke «ved».',
    topic: 'sted',
    level: 1,
    de: 'Die Kinder übernachten am Wochenende bei den Großeltern.',
  },
  {
    id: 'sted-bo-hos-meg',
    prompt: 'Du kan bo ___ meg mens du er i Oslo.',
    answer: 'hos',
    options: ['hos', 'til', 'i', 'på'],
    explanation: '«Hos» + person = hjemme hos den personen: bo hos meg, sove hos en venn.',
    topic: 'sted',
    level: 1,
    de: 'Du kannst bei mir wohnen, solange du in Oslo bist.',
  },
  {
    id: 'sted-bord-ved-vinduet',
    prompt: 'Kan vi få et bord ___ vinduet?',
    answer: 'ved',
    options: ['ved', 'hos', 'på', 'til'],
    explanation: '«Ved» = like inntil: ved vinduet, ved døra, ved veggen.',
    topic: 'sted',
    level: 2,
    de: 'Können wir einen Tisch am Fenster bekommen?',
  },
  {
    id: 'sted-ved-siden-av',
    prompt: 'På kino satt hun ___ siden av meg.',
    answer: 'ved',
    options: ['ved', 'i', 'hos', 'til'],
    explanation: 'Fast uttrykk: «ved siden av» = rett inntil, på siden av.',
    topic: 'sted',
    level: 2,
    de: 'Im Kino saß sie neben mir.',
  },
  {
    id: 'sted-katten-under-senga',
    prompt: 'Katten gjemmer seg ___ senga, så vi ser bare halen som stikker ut.',
    answer: 'under',
    options: ['under', 'mellom', 'blant', 'gjennom'],
    explanation: '«Under» = lavere enn og dekket av noe: under senga, under bordet.',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-lampa-over-bordet',
    prompt: 'Lampa henger ___ bordet på kjøkkenet.',
    answer: 'over',
    options: ['over', 'mellom', 'gjennom', 'mot'],
    explanation: '«Over» = høyere enn, uten berøring. Ligger noe oppå, bruker vi «på».',
    topic: 'sted',
    level: 1,
    de: 'Die Lampe hängt über dem Tisch in der Küche.',
  },
  {
    id: 'sted-kosten-bak-dora',
    prompt: 'Kosten står ___ døra, så du ser den ikke når døra er åpen.',
    answer: 'bak',
    options: ['bak', 'mellom', 'gjennom', 'blant'],
    explanation: '«Bak» = på baksiden av noe, skjult for den som står foran.',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-bak-meg-i-koen',
    prompt: 'Han sto rett ___ meg i køen, så jeg kom før ham.',
    answer: 'bak',
    options: ['bak', 'over', 'mellom', 'gjennom'],
    explanation: 'I en kø står den som kommer etter deg, «bak» deg.',
    topic: 'sted',
    level: 2,
  },
  {
    id: 'sted-bilen-foran-huset',
    prompt: 'Bilen er parkert ___ huset, rett ved inngangen.',
    answer: 'foran',
    options: ['foran', 'over', 'mellom', 'gjennom'],
    explanation: '«Foran» = på forsiden av noe. Inngangen er på forsiden, så bilen står der.',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-foran-tv',
    prompt: 'Barna sitter ___ TV-en hele kvelden.',
    answer: 'foran',
    options: ['foran', 'over', 'mellom', 'gjennom'],
    explanation: 'Man sitter «foran» skjermen, med ansiktet vendt mot den.',
    topic: 'sted',
    level: 1,
    de: 'Die Kinder sitzen den ganzen Abend vor dem Fernseher.',
  },
  {
    id: 'sted-tale-foran-klassen',
    prompt: 'Hun holdt en tale ___ hele klassen.',
    answer: 'foran',
    options: ['foran', 'mellom', 'gjennom', 'blant'],
    explanation: '«Foran» + publikum: stå foran klassen, synge foran mange. «For klassen» er også mulig.',
    topic: 'sted',
    level: 2,
  },
  {
    id: 'sted-mellom-oss-to',
    prompt: 'Dette blir ___ oss to, ikke si det til noen.',
    answer: 'mellom',
    options: ['mellom', 'blant', 'gjennom', 'over'],
    explanation: '«Mellom oss» = en hemmelighet. Med to personer brukes «mellom», ikke «blant».',
    topic: 'sted',
    level: 2,
    de: 'Das bleibt unter uns beiden, sag es niemandem.',
  },
  {
    id: 'sted-bygda-mellom-fjell',
    prompt: 'Bygda ligger ___ to høye fjell.',
    answer: 'mellom',
    options: ['mellom', 'blant', 'gjennom', 'hos'],
    explanation: 'Med nøyaktig to størrelser: «mellom». Med flere: «blant».',
    topic: 'sted',
    level: 1,
  },
  {
    id: 'sted-blant-de-beste',
    prompt: 'Han er ___ de beste spillerne i landet.',
    answer: 'blant',
    options: ['blant', 'mellom', 'over', 'gjennom'],
    explanation: '«Blant» = en del av en større gruppe: blant de beste, blant vennene mine.',
    topic: 'sted',
    level: 2,
    de: 'Er gehört zu den besten Spielern des Landes.',
  },
  {
    id: 'sted-populaer-blant',
    prompt: 'Læreren er populær ___ elevene.',
    answer: 'blant',
    options: ['blant', 'mellom', 'gjennom', 'over'],
    explanation: '«Populær blant» + en gruppe. «Populær hos» brukes også.',
    topic: 'sted',
    level: 2,
  },
  {
    id: 'sted-under-null',
    prompt: 'Det er ti grader ___ null i dag, så kle deg godt.',
    answer: 'under',
    options: ['under', 'mellom', 'bak', 'uten'],
    explanation: '«Under null» = kaldere enn null grader, det samme som «minus ti».',
    topic: 'sted',
    level: 2,
    de: 'Heute sind es zehn Grad unter null.',
  },
  {
    id: 'sted-over-hundre',
    prompt: 'Det kom ___ hundre mennesker på festen, flere enn vi hadde regnet med.',
    answer: 'over',
    options: ['over', 'blant', 'gjennom', 'ved'],
    explanation: '«Over» + tall = mer enn: over hundre, over 18 år.',
    topic: 'sted',
    level: 2,
  },
  {
    id: 'sted-under-18',
    prompt: 'Ungdom ___ 18 år får ikke kjøpe alkohol.',
    answer: 'under',
    options: ['under', 'mellom', 'blant', 'uten'],
    explanation: '«Under» + alder = yngre enn: under 18 år.',
    topic: 'sted',
    level: 2,
    de: 'Jugendliche unter 18 Jahren dürfen keinen Alkohol kaufen.',
  },

  // --- Stedsnavn: i / på ------------------------------------------------------
  {
    id: 'stedsnavn-regner-bergen',
    prompt: 'Det regner mye ___ Bergen.',
    answer: 'i',
    options: ['i', 'på', 'til', 'hos'],
    explanation: 'De fleste byer tar «i»: i Bergen, i Oslo, i Tromsø.',
    topic: 'stedsnavn',
    level: 1,
  },
  {
    id: 'stedsnavn-vokste-opp-hamar',
    prompt: 'Hun vokste opp ___ Hamar, men studerer i Oslo nå.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation:
      'Noen byer, særlig på Østlandet, tar «på»: på Hamar, på Gjøvik, på Lillehammer. Det er tradisjon, ikke regel.',
    topic: 'stedsnavn',
    level: 3,
    de: 'Sie ist in Hamar aufgewachsen, studiert jetzt aber in Oslo.',
  },
  {
    id: 'stedsnavn-ol-lillehammer',
    prompt: 'De olympiske vinterlekene i 1994 ble arrangert ___ Lillehammer.',
    answer: 'på',
    options: ['på', 'i', 'til', 'fra'],
    explanation: 'Lillehammer tar «på», som Hamar og Gjøvik. Slike unntak må læres ett for ett.',
    topic: 'stedsnavn',
    level: 3,
  },
  {
    id: 'stedsnavn-nordlys-island',
    prompt: 'Vi så nordlys ___ Island.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation: 'Øyer tar «på», også når øya er et eget land: på Island, på Malta, på Kreta.',
    topic: 'stedsnavn',
    level: 3,
    de: 'Wir haben auf Island Polarlichter gesehen.',
  },
  {
    id: 'stedsnavn-isbjorn-svalbard',
    prompt: 'Det finnes isbjørn ___ Svalbard.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation: 'Svalbard tar «på», som mange øyer. Lofoten og Vesterålen tar derimot «i».',
    topic: 'stedsnavn',
    level: 2,
  },
  {
    id: 'stedsnavn-vestlandet',
    prompt: 'Det regner mer ___ Vestlandet enn på Østlandet.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation: 'Landsdelene tar «på»: på Vestlandet, på Sørlandet. Men: i Nord-Norge og i Trøndelag.',
    topic: 'stedsnavn',
    level: 2,
  },
  {
    id: 'stedsnavn-nord-norge',
    prompt: 'Han kommer fra en liten bygd ___ Nord-Norge.',
    answer: 'i',
    options: ['i', 'på', 'til', 'hos'],
    explanation: '«I Nord-Norge» og «i Trøndelag», men «på Vestlandet» og «på Østlandet».',
    topic: 'stedsnavn',
    level: 2,
  },
  {
    id: 'stedsnavn-leilighet-kreta',
    prompt: 'De har kjøpt en leilighet ___ Kreta.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation: 'Øyer tar «på»: på Kreta, på Mallorca, på Gran Canaria.',
    topic: 'stedsnavn',
    level: 2,
    de: 'Sie haben eine Wohnung auf Kreta gekauft.',
  },

  // --- Bevegelse --------------------------------------------------------------
  {
    id: 'bevegelse-reiser-bergen',
    prompt: 'Vi reiser ___ Bergen på fredag.',
    answer: 'til',
    options: ['til', 'på', 'hos', 'ved'],
    explanation: 'Bevegelse med et mål: «til». Å være der = «i Bergen».',
    topic: 'bevegelse',
    level: 1,
    de: 'Wir reisen am Freitag nach Bergen.',
  },
  {
    id: 'bevegelse-katten-opp-pa-bordet',
    prompt: 'Katten hoppet opp ___ bordet og la seg der.',
    answer: 'på',
    options: ['på', 'i', 'til', 'ved'],
    explanation: 'Retning mot en flate: «opp på». Resultatet er at katten ligger på bordet.',
    topic: 'bevegelse',
    level: 2,
  },
  {
    id: 'bevegelse-kommer-fra-tyskland',
    prompt: 'Hun kommer opprinnelig ___ Tyskland, men bor i Norge nå.',
    answer: 'fra',
    options: ['fra', 'i', 'av', 'hos'],
    explanation: '«Fra» markerer utgangspunkt og opprinnelse: komme fra Tyskland.',
    topic: 'bevegelse',
    level: 1,
    de: 'Sie kommt ursprünglich aus Deutschland, wohnt aber jetzt in Norwegen.',
  },
  {
    id: 'bevegelse-gjennom-skogen',
    prompt: 'Vi gikk ___ skogen og kom ut på den andre siden.',
    answer: 'gjennom',
    options: ['gjennom', 'mot', 'mellom', 'hos'],
    explanation: '«Gjennom» = inn på én side og ut på den andre.',
    topic: 'bevegelse',
    level: 2,
  },
  {
    id: 'bevegelse-mot-vinden',
    prompt: 'Vi syklet ___ vinden hele veien hjem, så det gikk tregt.',
    answer: 'mot',
    options: ['mot', 'med', 'til', 'fra'],
    explanation: '«Mot» = i motsatt retning av: mot vinden, mot strømmen. «Med vinden» ville gått lett.',
    topic: 'bevegelse',
    level: 2,
    allowedContrasts: ['fra'],
  },
  {
    id: 'bevegelse-opp-av-lommen',
    prompt: 'Hun tok brevet opp ___ lommen.',
    answer: 'av',
    options: ['av', 'fra', 'i', 'på'],
    explanation: 'Ut fra innsiden av noe: «opp av lommen», «ut av vesken». Det speiler «i lommen».',
    topic: 'bevegelse',
    level: 3,
  },
  {
    id: 'bevegelse-hjem-fra-jobben',
    prompt: 'Når kommer du hjem ___ jobben?',
    answer: 'fra',
    options: ['fra', 'av', 'i', 'ved'],
    explanation: '«Fra» = utgangspunktet for bevegelsen: hjem fra jobben, hjem fra skolen.',
    topic: 'bevegelse',
    level: 1,
    de: 'Wann kommst du von der Arbeit nach Hause?',
  },
  {
    id: 'bevegelse-flyttet-fra-polen',
    prompt: 'Familien flyttet ___ Polen til Norge for ti år siden.',
    answer: 'fra',
    options: ['fra', 'av', 'i', 'ved'],
    explanation: 'Fast par: «fra» et utgangspunkt «til» et mål.',
    topic: 'bevegelse',
    level: 1,
    de: 'Die Familie ist vor zehn Jahren von Polen nach Norwegen gezogen.',
  },
  {
    id: 'bevegelse-toget-fra-oslo',
    prompt: 'Toget ___ Oslo er forsinket, så vi må vente på stasjonen.',
    answer: 'fra',
    options: ['fra', 'av', 'ved', 'hos'],
    explanation: '«Toget fra Oslo» kommer derfra. «Toget til Oslo» skal dit.',
    topic: 'bevegelse',
    level: 1,
  },
  {
    id: 'bevegelse-ned-fra-taket',
    prompt: 'Katten klatret ned ___ taket.',
    answer: 'fra',
    options: ['fra', 'i', 'ved', 'hos'],
    explanation: '«Ned fra» = bort fra et høyere sted. «Ned av taket» er også mulig.',
    topic: 'bevegelse',
    level: 2,
  },
  {
    id: 'bevegelse-over-gata',
    prompt: 'Se deg godt for før du går ___ gata.',
    answer: 'over',
    options: ['over', 'mellom', 'blant', 'hos'],
    explanation: '«Over» = fra den ene siden til den andre: gå over gata, over brua.',
    topic: 'bevegelse',
    level: 1,
  },
  {
    id: 'bevegelse-over-brua',
    prompt: 'Vi kjørte ___ brua til Sverige.',
    answer: 'over',
    options: ['over', 'gjennom', 'mellom', 'blant'],
    explanation: 'Man kjører «over» en bru, men «gjennom» en tunnel.',
    topic: 'bevegelse',
    level: 2,
    de: 'Wir sind über die Brücke nach Schweden gefahren.',
  },
  {
    id: 'bevegelse-gjennom-vinduet',
    prompt: 'Sola skinner inn ___ vinduet.',
    answer: 'gjennom',
    options: ['gjennom', 'mellom', 'over', 'blant'],
    explanation: 'Lyset kommer inn på den ene siden av glasset og ut på den andre: «gjennom».',
    topic: 'bevegelse',
    level: 1,
  },
  {
    id: 'bevegelse-gjennom-kjokkenet',
    prompt: 'Vi må gå ___ kjøkkenet for å komme ut i hagen.',
    answer: 'gjennom',
    options: ['gjennom', 'mellom', 'blant', 'over'],
    explanation: '«Gjennom» et rom = inn i det og ut på den andre siden.',
    topic: 'bevegelse',
    level: 2,
  },
  {
    id: 'bevegelse-gikk-mot-dora',
    prompt: 'Hun gikk ___ døra, men snudde før hun kom fram.',
    answer: 'mot',
    options: ['mot', 'til', 'av', 'hos'],
    explanation: '«Mot» = i retning av, uten at man når fram. «Til» betyr at man kommer fram.',
    topic: 'bevegelse',
    level: 3,
  },
  {
    id: 'bevegelse-til-fjells',
    prompt: 'Om vinteren drar vi ___ fjells hver helg.',
    answer: 'til',
    options: ['til', 'på', 'i', 'mot'],
    explanation: 'Fast uttrykk med gammel s-ending: til fjells, til sjøs, til sengs.',
    topic: 'bevegelse',
    level: 3,
  },
  {
    id: 'bevegelse-til-sengs',
    prompt: 'Barna må gå ___ sengs klokka åtte.',
    answer: 'til',
    options: ['til', 'i', 'på', 'mot'],
    explanation: 'Fast uttrykk: «gå til sengs» = legge seg. Samme mønster: til fots, til fjells.',
    topic: 'bevegelse',
    level: 3,
    de: 'Die Kinder müssen um acht Uhr ins Bett gehen.',
  },
  {
    id: 'bevegelse-til-fots',
    prompt: 'Jeg går ___ fots til jobben.',
    answer: 'til',
    options: ['til', 'på', 'med', 'i'],
    explanation: 'Fast uttrykk: «til fots» = gående. Tysk «zu Fuß».',
    topic: 'bevegelse',
    level: 2,
    de: 'Ich gehe zu Fuß zur Arbeit.',
  },
  {
    id: 'bevegelse-toget-til-oslo',
    prompt: 'Toget ___ Oslo går fra spor tre.',
    answer: 'til',
    options: ['til', 'hos', 'ved', 'av'],
    explanation: 'Målet for reisen tar «til»: toget til Oslo, flyet til Paris.',
    topic: 'bevegelse',
    level: 1,
    de: 'Der Zug nach Oslo fährt von Gleis drei ab.',
  },

  // --- Tid --------------------------------------------------------------------
  {
    id: 'tid-om-morgenen',
    prompt: 'Jeg står opp klokka sju ___ morgenen.',
    answer: 'om',
    options: ['om', 'i', 'ved', 'til'],
    explanation:
      'Del av døgnet som gjentar seg: «om morgenen», «om kvelden». «I morgen» (uten -en) betyr dagen etter i dag.',
    topic: 'tid',
    level: 2,
    de: 'Ich stehe morgens um sieben Uhr auf.',
  },
  {
    id: 'tid-pa-mandag',
    prompt: 'Vi sees ___ mandag.',
    answer: 'på',
    options: ['på', 'i', 'om', 'ved'],
    explanation: 'Ukedager tar «på»: på mandag, på lørdag. «Om mandagen» = hver mandag.',
    topic: 'tid',
    level: 1,
    de: 'Wir sehen uns am Montag.',
  },
  {
    id: 'tid-om-fem-minutter',
    prompt: 'Filmen begynner ___ fem minutter.',
    answer: 'om',
    options: ['om', 'i', 'på', 'ved'],
    explanation: '«Om» + tidsrom = så lang tid fra nå: om fem minutter, om en uke. «I fem minutter» = varighet.',
    topic: 'tid',
    level: 2,
    de: 'Der Film beginnt in fünf Minuten.',
  },
  {
    id: 'tid-i-fem-ar',
    prompt: 'Jeg har bodd her ___ fem år.',
    answer: 'i',
    options: ['i', 'om', 'på', 'siden'],
    explanation: 'Varighet: «i fem år». Tysk «seit fünf Jahren» blir ikke «siden»: «siden» tar et startpunkt (siden 2020).',
    topic: 'tid',
    level: 2,
    de: 'Ich wohne seit fünf Jahren hier.',
  },
  {
    id: 'tid-siden-mandag',
    prompt: 'Hun har vært syk ___ mandag.',
    answer: 'siden',
    options: ['siden', 'i', 'om', 'på'],
    explanation: '«Siden» + startpunkt når tilstanden fortsatt varer.',
    topic: 'tid',
    level: 2,
    de: 'Sie ist seit Montag krank.',
  },
  {
    id: 'tid-etter-jobb',
    prompt: 'Vi spiser middag ___ jobb, når vi kommer hjem.',
    answer: 'etter',
    options: ['etter', 'før', 'under', 'ved'],
    explanation: '«Etter» = senere enn. «Når vi kommer hjem» utelukker «før» og «under».',
    topic: 'tid',
    level: 1,
    allowedContrasts: ['før', 'under'],
  },
  {
    id: 'tid-under-forelesningen',
    prompt: 'Han sovnet ___ forelesningen.',
    answer: 'under',
    options: ['under', 'ved', 'mot', 'hos'],
    explanation: '«Under» = mens noe pågår: under forelesningen, under møtet, under krigen.',
    topic: 'tid',
    level: 2,
  },
  {
    id: 'tid-pa-ti-minutter',
    prompt: 'Jeg klarte oppgaven ___ ti minutter.',
    answer: 'på',
    options: ['på', 'i', 'om', 'til'],
    explanation: 'Tid brukt på å fullføre noe: «på ti minutter». «I ti minutter» = varighet uten mål.',
    topic: 'tid',
    level: 3,
    de: 'Ich habe die Aufgabe in zehn Minuten geschafft.',
  },
  {
    id: 'tid-fra-atte-til-fire',
    prompt: 'Butikken er åpen ___ åtte til fire.',
    answer: 'fra',
    options: ['fra', 'i', 'mellom', 'siden'],
    explanation: 'Fast par: «fra … til …» for et tidsrom. «Mellom» krever «og»: mellom åtte og fire.',
    topic: 'tid',
    level: 1,
  },
  {
    id: 'tid-fodt-i-1990',
    prompt: 'Han ble født ___ 1990.',
    answer: 'i',
    options: ['i', 'på', 'ved', 'om'],
    explanation: 'År og måneder tar «i»: i 1990, i mai, i fjor.',
    topic: 'tid',
    level: 1,
  },
  {
    id: 'tid-for-to-ar-siden',
    prompt: 'Jeg flyttet hit for to år ___.',
    answer: 'siden',
    options: ['siden', 'om', 'etter', 'i'],
    explanation: '«For … siden» peker bakover i tid. Tysk «vor zwei Jahren» blir ikke «før to år».',
    topic: 'tid',
    level: 2,
    de: 'Ich bin vor zwei Jahren hierher gezogen.',
  },
  {
    id: 'tid-siden-2015',
    prompt: 'Vi har bodd i Trondheim ___ 2015.',
    answer: 'siden',
    options: ['siden', 'om', 'på', 'ved'],
    explanation: '«Siden» + startpunkt, og tilstanden varer fortsatt.',
    topic: 'tid',
    level: 1,
    de: 'Wir wohnen seit 2015 in Trondheim.',
  },
  {
    id: 'tid-lenge-siden-sist',
    prompt: 'Lenge ___ sist! Hvordan har du hatt det?',
    answer: 'siden',
    options: ['siden', 'om', 'fra', 'på'],
    explanation: 'Fast hilsen når man ikke har sett hverandre på lenge.',
    topic: 'tid',
    level: 3,
    de: 'Lange nicht gesehen! Wie geht es dir?',
  },
  {
    id: 'tid-for-maten',
    prompt: 'Husk å vaske hendene ___ maten.',
    answer: 'før',
    options: ['før', 'om', 'i', 'hos'],
    explanation: '«Før» = tidligere enn. «Før maten» = før man begynner å spise.',
    topic: 'tid',
    level: 1,
    de: 'Denk daran, dir vor dem Essen die Hände zu waschen.',
  },
  {
    id: 'tid-for-klokka-ti',
    prompt: 'Du må levere oppgaven ___ klokka ti på fredag.',
    answer: 'før',
    options: ['før', 'om', 'i', 'på'],
    explanation: 'En frist: «før klokka ti». «Innen klokka ti» betyr det samme.',
    topic: 'tid',
    level: 2,
  },
  {
    id: 'tid-for-avgang',
    prompt: 'Han var på stasjonen to minutter ___ avgang, så han rakk toget.',
    answer: 'før',
    options: ['før', 'om', 'i', 'mot'],
    explanation: 'Han kom tidligere enn toget gikk: «før avgang».',
    topic: 'tid',
    level: 2,
  },
  {
    id: 'tid-for-i-tiden',
    prompt: 'Folk gikk mye mer til fots ___ i tiden.',
    answer: 'før',
    options: ['før', 'om', 'ved', 'mot'],
    explanation: 'Fast uttrykk: «før i tiden» = i gamle dager.',
    topic: 'tid',
    level: 3,
    de: 'Früher sind die Leute viel mehr zu Fuß gegangen.',
  },
  {
    id: 'tid-etter-hvert',
    prompt: 'Det er vanskelig nå, men du blir vant til det ___ hvert.',
    answer: 'etter',
    options: ['etter', 'for', 'om', 'på'],
    explanation: 'Fast uttrykk: «etter hvert» = gradvis, litt etter litt.',
    topic: 'tid',
    level: 3,
    de: 'Es ist jetzt schwer, aber du gewöhnst dich nach und nach daran.',
  },
  {
    id: 'tid-en-etter-en',
    prompt: 'Elevene kom inn i klasserommet én ___ én.',
    answer: 'etter',
    options: ['etter', 'av', 'hos', 'ved'],
    explanation: '«Én etter én» = i rekkefølge, én om gangen.',
    topic: 'tid',
    level: 2,
  },
  {
    id: 'tid-i-morges',
    prompt: 'Jeg drakk bare kaffe ___ morges, så nå er jeg sulten.',
    answer: 'i',
    options: ['i', 'om', 'på', 'til'],
    explanation: '«I morges» = tidligere i dag. «I morgen» = dagen etter i dag.',
    topic: 'tid',
    level: 2,
    de: 'Ich habe heute Morgen nur Kaffee getrunken.',
  },
  {
    id: 'tid-i-fjor',
    prompt: 'Vi flyttet hit ___ fjor.',
    answer: 'i',
    options: ['i', 'på', 'om', 'til'],
    explanation: '«I fjor» = året før i år. Samme mønster: i går, i forgårs.',
    topic: 'tid',
    level: 2,
    de: 'Wir sind letztes Jahr hierher gezogen.',
  },
  {
    id: 'tid-i-natt',
    prompt: 'Jeg sov dårlig ___ natt, så nå er jeg trøtt.',
    answer: 'i',
    options: ['i', 'om', 'på', 'ved'],
    explanation: '«I natt» = natten som var eller natten som kommer. Vaner tar «om natta».',
    topic: 'tid',
    level: 2,
    de: 'Ich habe letzte Nacht schlecht geschlafen.',
  },
  {
    id: 'tid-om-natta',
    prompt: 'Ugler jakter mest ___ natta.',
    answer: 'om',
    options: ['om', 'i', 'ved', 'til'],
    explanation: 'Det som gjentar seg, tar «om» + bestemt form: om natta, om dagen, om sommeren.',
    topic: 'tid',
    level: 2,
    de: 'Eulen jagen meistens nachts.',
  },
  {
    id: 'tid-tidlig-pa-morgenen',
    prompt: 'Det var kaldt tidlig ___ morgenen, men varmt om ettermiddagen.',
    answer: 'på',
    options: ['på', 'i', 'ved', 'til'],
    explanation: 'Med «tidlig» og «sent» brukes ofte «på»: tidlig på morgenen, sent på kvelden.',
    topic: 'tid',
    level: 3,
  },
  {
    id: 'tid-i-tide',
    prompt: 'Toget var forsinket, men vi kom fram ___ tide.',
    answer: 'i',
    options: ['i', 'på', 'om', 'til'],
    explanation: '«I tide» = tidsnok. «Det er på tide» betyr at noe bør skje nå.',
    topic: 'tid',
    level: 3,
    de: 'Der Zug hatte Verspätung, aber wir sind rechtzeitig angekommen.',
  },
  {
    id: 'tid-pa-tide',
    prompt: 'Det er ___ tide at du rydder rommet ditt.',
    answer: 'på',
    options: ['på', 'i', 'om', 'til'],
    explanation: '«Det er på tide» = nå bør det skje. «I tide» betyr tidsnok.',
    topic: 'tid',
    level: 3,
    de: 'Es wird Zeit, dass du dein Zimmer aufräumst.',
  },
  {
    id: 'tid-under-middagen',
    prompt: 'Vi snakker ikke i telefonen ___ middagen.',
    answer: 'under',
    options: ['under', 'mot', 'hos', 'blant'],
    explanation: '«Under» om tid = mens noe pågår: under middagen, under kampen.',
    topic: 'tid',
    level: 2,
  },
  {
    id: 'tid-om-gangen',
    prompt: 'Han spiste tre kaker ___ gangen.',
    answer: 'om',
    options: ['om', 'av', 'ved', 'til'],
    explanation: 'Fast uttrykk: «tre om gangen» = tre samtidig.',
    topic: 'tid',
    level: 3,
    de: 'Er hat drei Kuchen auf einmal gegessen.',
  },
  {
    id: 'tid-for-forste-gang',
    prompt: 'Jeg var i Norge ___ første gang i 2010.',
    answer: 'for',
    options: ['for', 'i', 'på', 'til'],
    explanation: 'Fast uttrykk: «for første gang». Tysk «zum ersten Mal» blir ikke «til».',
    topic: 'tid',
    level: 2,
    de: 'Ich war 2010 zum ersten Mal in Norwegen.',
  },
  {
    id: 'tid-mellom-to-og-tre',
    prompt: 'Jeg er hjemme ___ to og tre i ettermiddag.',
    answer: 'mellom',
    options: ['mellom', 'fra', 'blant', 'om'],
    explanation: '«Mellom» + «og» for et tidsrom. Med «fra» må det være «til»: fra to til tre.',
    topic: 'tid',
    level: 2,
  },

  // --- Verb + preposisjon -----------------------------------------------------
  {
    id: 'verb-venter-pa-bussen',
    prompt: 'Jeg venter ___ bussen.',
    answer: 'på',
    options: ['på', 'for', 'til', 'etter'],
    explanation: 'Fast verbpar: «vente på» noe eller noen.',
    topic: 'verb',
    level: 1,
    de: 'Ich warte auf den Bus.',
  },
  {
    id: 'verb-snakket-om-ferien',
    prompt: 'Vi snakket ___ ferien i går.',
    answer: 'om',
    options: ['om', 'av', 'for', 'til'],
    explanation: '«Snakke om» = tema. «Snakke med» = samtalepartner.',
    topic: 'verb',
    level: 1,
  },
  {
    id: 'verb-ba-om-vann',
    prompt: 'Hun ba meg ___ et glass vann.',
    answer: 'om',
    options: ['om', 'for', 'av', 'mot'],
    explanation: '«Be noen om noe» — be om, ikke be for. «Be noen på middag» = invitere.',
    topic: 'verb',
    level: 3,
  },
  {
    id: 'verb-handler-om',
    prompt: 'Boka handler ___ en ung jente.',
    answer: 'om',
    options: ['om', 'av', 'med', 'på'],
    explanation: '«Handle om» = ha som tema. «Handle med» = drive handel.',
    topic: 'verb',
    level: 2,
    allowedContrasts: ['med'],
  },
  {
    id: 'verb-tror-pa-deg',
    prompt: 'Jeg tror ___ deg.',
    answer: 'på',
    options: ['på', 'i', 'til', 'av'],
    explanation: '«Tro på» noen eller noe. Uten preposisjon: «jeg tror at …».',
    topic: 'verb',
    level: 2,
  },
  {
    id: 'verb-gleder-seg-til',
    prompt: 'Vi gleder oss ___ sommeren.',
    answer: 'til',
    options: ['til', 'på', 'for', 'om'],
    explanation: '«Glede seg til» noe som kommer. Tysk «sich freuen auf» blir ikke «på».',
    topic: 'verb',
    level: 2,
    de: 'Wir freuen uns auf den Sommer.',
  },
  {
    id: 'verb-kommer-an-pa',
    prompt: 'Det kommer an ___ været.',
    answer: 'på',
    options: ['på', 'av', 'i', 'med'],
    explanation: 'Fast uttrykk: «komme an på» = avhenge av.',
    topic: 'verb',
    level: 3,
  },
  {
    id: 'verb-passer-pa-barna',
    prompt: 'Han passer ___ barna hver torsdag.',
    answer: 'på',
    options: ['på', 'av', 'med', 'om'],
    explanation: '«Passe på» = ta vare på, holde øye med. «Passe til» = stemme overens med.',
    topic: 'verb',
    level: 2,
  },
  {
    id: 'verb-leter-etter',
    prompt: 'Jeg leter ___ nøklene mine.',
    answer: 'etter',
    options: ['etter', 'på', 'for', 'om'],
    explanation: '«Lete etter» = prøve å finne. Tysk «suchen nach».',
    topic: 'verb',
    level: 2,
    de: 'Ich suche nach meinen Schlüsseln.',
  },
  {
    id: 'verb-oppkalt-etter',
    prompt: 'Hun er oppkalt ___ bestemoren sin.',
    answer: 'etter',
    options: ['etter', 'fra', 'til', 'om'],
    explanation: 'Fast uttrykk: «oppkalt etter» noen = har fått navnet sitt fra den personen.',
    topic: 'verb',
    level: 3,
    de: 'Sie ist nach ihrer Großmutter benannt.',
  },
  {
    id: 'verb-lengter-etter',
    prompt: 'Jeg lengter ___ sommeren.',
    answer: 'etter',
    options: ['etter', 'på', 'for', 'av'],
    explanation: '«Lengte etter» = savne og ønske seg. Tysk «sich sehnen nach».',
    topic: 'verb',
    level: 3,
    de: 'Ich sehne mich nach dem Sommer.',
  },
  {
    id: 'verb-gikk-etter-planen',
    prompt: 'Alt gikk ___ planen, og vi ble ferdige i tide.',
    answer: 'etter',
    options: ['etter', 'av', 'om', 'for'],
    explanation: '«Etter planen» = slik det var planlagt.',
    topic: 'verb',
    level: 3,
    de: 'Alles lief nach Plan, und wir wurden rechtzeitig fertig.',
  },
  {
    id: 'verb-hjelpe-med',
    prompt: 'Kan du hjelpe meg ___ leksene?',
    answer: 'med',
    options: ['med', 'på', 'for', 'til'],
    explanation: '«Hjelpe noen med noe». Tysk «bei den Hausaufgaben» blir ikke «ved».',
    topic: 'verb',
    level: 2,
    de: 'Kannst du mir bei den Hausaufgaben helfen?',
  },
  {
    id: 'verb-sluttet-med',
    prompt: 'Han har sluttet ___ å røyke.',
    answer: 'med',
    options: ['med', 'av', 'på', 'til'],
    explanation: '«Slutte med» + aktivitet. Med jobb eller skole: «slutte i jobben».',
    topic: 'verb',
    level: 2,
    de: 'Er hat mit dem Rauchen aufgehört.',
  },
  {
    id: 'verb-slo-opp-med',
    prompt: 'Hun slo opp ___ kjæresten sin i helgen.',
    answer: 'med',
    options: ['med', 'fra', 'av', 'til'],
    explanation: 'Fast uttrykk: «slå opp med» noen = avslutte et kjæresteforhold.',
    topic: 'verb',
    level: 3,
    de: 'Sie hat am Wochenende mit ihrem Freund Schluss gemacht.',
  },
  {
    id: 'verb-ble-kjent-med',
    prompt: 'Vi ble kjent ___ hverandre på universitetet.',
    answer: 'med',
    options: ['med', 'av', 'til', 'for'],
    explanation: '«Bli kjent med» = møte og lære å kjenne. «Kjent for» = berømt for.',
    topic: 'verb',
    level: 2,
    de: 'Wir haben uns an der Universität kennengelernt.',
  },
  {
    id: 'verb-sporre-om',
    prompt: 'Kan jeg spørre deg ___ noe?',
    answer: 'om',
    options: ['om', 'for', 'på', 'av'],
    explanation: '«Spørre noen om noe». Tysk «jemanden etwas fragen» har ingen preposisjon.',
    topic: 'verb',
    level: 2,
    de: 'Darf ich dich etwas fragen?',
  },
  {
    id: 'verb-bryr-seg-om',
    prompt: 'Han bryr seg ikke ___ hva andre mener.',
    answer: 'om',
    options: ['om', 'for', 'på', 'av'],
    explanation: 'Fast uttrykk: «bry seg om» = være opptatt av, ta hensyn til.',
    topic: 'verb',
    level: 3,
  },
  {
    id: 'verb-dromte-om',
    prompt: 'Jeg drømte ___ deg i natt.',
    answer: 'om',
    options: ['om', 'av', 'for', 'til'],
    explanation: '«Drømme om» noe eller noen. Tysk «von dir träumen» blir ikke «av».',
    topic: 'verb',
    level: 2,
    de: 'Ich habe heute Nacht von dir geträumt.',
  },
  {
    id: 'verb-la-merke-til',
    prompt: 'La du merke ___ den nye frisyren hennes?',
    answer: 'til',
    options: ['til', 'på', 'om', 'av'],
    explanation: 'Fast uttrykk: «legge merke til» = oppdage, se.',
    topic: 'verb',
    level: 3,
    de: 'Hast du ihre neue Frisur bemerkt?',
  },
  {
    id: 'verb-ta-hensyn-til',
    prompt: 'Vi må ta hensyn ___ naboene og ikke spille høy musikk.',
    answer: 'til',
    options: ['til', 'på', 'for', 'om'],
    explanation: 'Fast uttrykk: «ta hensyn til». Tysk «Rücksicht nehmen auf» blir ikke «på».',
    topic: 'verb',
    level: 3,
    de: 'Wir müssen Rücksicht auf die Nachbarn nehmen.',
  },
  {
    id: 'verb-gar-ut-fra',
    prompt: 'Jeg går ut ___ at du kommer på festen.',
    answer: 'fra',
    options: ['fra', 'av', 'om', 'for'],
    explanation: '«Gå ut fra at» = regne med, anta. Tysk «davon ausgehen».',
    topic: 'verb',
    level: 3,
    de: 'Ich gehe davon aus, dass du zur Party kommst.',
  },
  {
    id: 'verb-bestemt-seg-for',
    prompt: 'Hun har bestemt seg ___ å flytte til Bergen.',
    answer: 'for',
    options: ['for', 'på', 'av', 'med'],
    explanation: '«Bestemme seg for» noe = ta en beslutning.',
    topic: 'verb',
    level: 3,
    de: 'Sie hat sich entschieden, nach Bergen zu ziehen.',
  },
  {
    id: 'verb-deltok-i',
    prompt: 'Alle elevene deltok ___ konkurransen.',
    answer: 'i',
    options: ['i', 'til', 'med', 'for'],
    explanation: '«Delta i» noe. I talespråk hører man også «delta på».',
    topic: 'verb',
    level: 2,
    de: 'Alle Schüler haben an dem Wettbewerb teilgenommen.',
  },
  {
    id: 'verb-setter-pris-pa',
    prompt: 'Jeg setter stor pris ___ hjelpen din.',
    answer: 'på',
    options: ['på', 'for', 'til', 'av'],
    explanation: 'Fast uttrykk: «sette pris på» = være takknemlig for, like godt.',
    topic: 'verb',
    level: 3,
    de: 'Ich weiß deine Hilfe sehr zu schätzen.',
  },
  {
    id: 'verb-horer-pa-musikk',
    prompt: 'Hun hører ___ musikk hele dagen.',
    answer: 'på',
    options: ['på', 'for', 'i', 'med'],
    explanation: '«Høre på» = lytte til. Tysk «Musik hören» har ingen preposisjon.',
    topic: 'verb',
    level: 2,
    de: 'Sie hört den ganzen Tag Musik.',
  },
  {
    id: 'verb-tenker-pa',
    prompt: 'Jeg tenker ofte ___ barndommen min.',
    answer: 'på',
    options: ['på', 'for', 'til', 'av'],
    explanation: '«Tenke på» noe eller noen. «Tenke over» = vurdere grundig.',
    topic: 'verb',
    level: 2,
    de: 'Ich denke oft an meine Kindheit.',
  },
  {
    id: 'verb-har-lyst-pa',
    prompt: 'Jeg har lyst ___ is.',
    answer: 'på',
    options: ['på', 'for', 'om', 'av'],
    explanation: '«Lyst på» + noe man vil ha, «lyst til å» + verb.',
    topic: 'verb',
    level: 2,
    de: 'Ich habe Lust auf Eis.',
  },
  {
    id: 'verb-har-rad-til',
    prompt: 'Vi har ikke råd ___ ny bil i år.',
    answer: 'til',
    options: ['til', 'på', 'for', 'av'],
    explanation: '«Ha råd til» = ha nok penger til noe.',
    topic: 'verb',
    level: 3,
    de: 'Wir können uns dieses Jahr kein neues Auto leisten.',
  },
  {
    id: 'verb-gikk-glipp-av',
    prompt: 'Du gikk glipp ___ en fin konsert i går.',
    answer: 'av',
    options: ['av', 'på', 'fra', 'om'],
    explanation: 'Fast uttrykk: «gå glipp av» = ikke få med seg.',
    topic: 'verb',
    level: 3,
    de: 'Du hast gestern ein schönes Konzert verpasst.',
  },
  {
    id: 'verb-ta-vare-pa',
    prompt: 'Ta godt vare ___ deg selv!',
    answer: 'på',
    options: ['på', 'for', 'om', 'til'],
    explanation: '«Ta vare på» = passe på, stelle godt med.',
    topic: 'verb',
    level: 2,
    de: 'Pass gut auf dich auf!',
  },
  {
    id: 'verb-ta-av-skoene',
    prompt: 'Ta ___ deg skoene i gangen.',
    answer: 'av',
    options: ['av', 'fra', 'til', 'om'],
    explanation: '«Ta av seg» klær og sko. Det motsatte er «ta på seg».',
    topic: 'verb',
    level: 2,
    de: 'Zieh dir im Flur die Schuhe aus.',
  },
  {
    id: 'verb-dode-av',
    prompt: 'Han døde ___ kreft i fjor.',
    answer: 'av',
    options: ['av', 'fra', 'for', 'om'],
    explanation: '«Dø av» en sykdom. «Dø for» brukes om en sak: dø for landet.',
    topic: 'verb',
    level: 3,
    de: 'Er ist letztes Jahr an Krebs gestorben.',
  },
  {
    id: 'verb-bestar-av',
    prompt: 'Vann består ___ hydrogen og oksygen.',
    answer: 'av',
    options: ['av', 'fra', 'med', 'for'],
    explanation: '«Bestå av» = være satt sammen av. Tysk «bestehen aus» blir ikke «fra».',
    topic: 'verb',
    level: 2,
    de: 'Wasser besteht aus Wasserstoff und Sauerstoff.',
  },
  {
    id: 'verb-stemte-mot',
    prompt: 'Flertallet stemte ___ forslaget, så det ble ikke vedtatt.',
    answer: 'mot',
    options: ['mot', 'til', 'av', 'gjennom'],
    explanation: '«Stemme mot» = si nei. Det motsatte er «stemme for».',
    topic: 'verb',
    level: 3,
  },
  {
    id: 'verb-spiller-mot',
    prompt: 'Norge spiller ___ Sverige i kveld.',
    answer: 'mot',
    options: ['mot', 'til', 'av', 'over'],
    explanation: 'Motstanderen i en kamp tar «mot»: Norge mot Sverige.',
    topic: 'verb',
    level: 1,
    de: 'Norwegen spielt heute Abend gegen Schweden.',
  },
  {
    id: 'verb-star-bak',
    prompt: 'Politiet vet ikke hvem som står ___ ranet.',
    answer: 'bak',
    options: ['bak', 'over', 'mellom', 'gjennom'],
    explanation: '«Stå bak» noe = ha planlagt eller utført det.',
    topic: 'verb',
    level: 3,
  },
  {
    id: 'verb-bak-rattet',
    prompt: 'Hvem satt ___ rattet da ulykken skjedde?',
    answer: 'bak',
    options: ['bak', 'over', 'gjennom', 'blant'],
    explanation: '«Bak rattet» = den som kjører. «Ved rattet» betyr det samme.',
    topic: 'verb',
    level: 3,
    de: 'Wer saß am Steuer, als der Unfall passierte?',
  },
  {
    id: 'verb-les-gjennom',
    prompt: 'Les ___ teksten en gang til før du leverer.',
    answer: 'gjennom',
    options: ['gjennom', 'mellom', 'mot', 'blant'],
    explanation: '«Lese gjennom» = lese hele, fra start til slutt.',
    topic: 'verb',
    level: 2,
    de: 'Lies den Text noch einmal durch, bevor du ihn abgibst.',
  },
  {
    id: 'verb-jobben-gjennom-en-venn',
    prompt: 'Hun fikk jobben ___ en venn som jobbet der.',
    answer: 'gjennom',
    options: ['gjennom', 'mellom', 'mot', 'over'],
    explanation: '«Gjennom» kan bety «ved hjelp av»: fikk jobben gjennom en venn.',
    topic: 'verb',
    level: 3,
    de: 'Sie hat den Job über einen Freund bekommen, der dort arbeitete.',
  },
  {
    id: 'verb-gikk-uten-a-si',
    prompt: 'Han gikk ___ å si ha det.',
    answer: 'uten',
    options: ['uten', 'av', 'om', 'til'],
    explanation: '«Uten å» + verb = og gjorde ikke det. Tysk «ohne … zu».',
    topic: 'verb',
    level: 2,
    de: 'Er ging, ohne Tschüss zu sagen.',
  },
  {
    id: 'verb-hils-fra-meg',
    prompt: 'Hils dem ___ meg!',
    answer: 'fra',
    options: ['fra', 'av', 'med', 'om'],
    explanation: '«Hilse fra» noen = gi videre en hilsen. Tysk «Grüß sie von mir».',
    topic: 'verb',
    level: 2,
    de: 'Grüß sie von mir!',
  },

  // --- Faste uttrykk: adjektiv og substantiv + preposisjon --------------------
  {
    id: 'uttrykk-flink-i',
    prompt: 'Hun er flink ___ matematikk.',
    answer: 'i',
    options: ['i', 'på', 'om', 'for'],
    explanation: '«Flink i» et fag, men «flink til å» gjøre noe.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-gift-med',
    prompt: 'Han er gift ___ en lærer.',
    answer: 'med',
    options: ['med', 'til', 'av', 'på'],
    explanation: 'Fast uttrykk: «gift med». Tysk «verheiratet mit» stemmer her.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-glad-i',
    prompt: 'Jeg er glad ___ deg.',
    answer: 'i',
    options: ['i', 'på', 'om', 'til'],
    explanation: '«Glad i» = å like noen eller noe svært godt. «Glad for» = takknemlig eller fornøyd med noe.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Ich habe dich lieb.',
  },
  {
    id: 'uttrykk-takk-for',
    prompt: 'Takk ___ hjelpen!',
    answer: 'for',
    options: ['for', 'av', 'til', 'om'],
    explanation: '«Takk for» + det du takker for, «takk til» + personen: takk til deg for hjelpen.',
    topic: 'fast-uttrykk',
    level: 1,
  },
  {
    id: 'uttrykk-interessert-i',
    prompt: 'Han er interessert ___ musikk.',
    answer: 'i',
    options: ['i', 'for', 'på', 'om'],
    explanation: 'Fast uttrykk: «interessert i». Tysk «sich interessieren für» frister til «for», men det er feil.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Er interessiert sich für Musik.',
  },
  {
    id: 'uttrykk-redd-for',
    prompt: 'Hun er redd ___ hunder.',
    answer: 'for',
    options: ['for', 'av', 'på', 'mot'],
    explanation: 'Fast uttrykk: «redd for».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Sie hat Angst vor Hunden.',
  },
  {
    id: 'uttrykk-lei-av',
    prompt: 'Jeg er lei ___ å vente.',
    answer: 'av',
    options: ['av', 'for', 'på', 'med'],
    explanation: '«Lei av» = har fått nok av noe. «Lei for» = lei seg over noe: «Jeg er lei for det».',
    topic: 'fast-uttrykk',
    level: 3,
  },
  {
    id: 'uttrykk-ga-pa-kino',
    prompt: 'Vi går ___ kino i kveld.',
    answer: 'på',
    options: ['på', 'til', 'i', 'mot'],
    explanation: 'Fast uttrykk: «gå på kino», selv om det er bevegelse.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-pa-ferie',
    prompt: 'Hun er ___ ferie denne uka.',
    answer: 'på',
    options: ['på', 'i', 'til', 'med'],
    explanation: 'Fast uttrykk: «på ferie», «på tur», «på jobb».',
    topic: 'fast-uttrykk',
    level: 1,
  },
  {
    id: 'uttrykk-pa-skolen',
    prompt: 'Barna er ___ skolen nå.',
    answer: 'på',
    options: ['på', 'hos', 'til', 'av'],
    explanation: '«På skolen» = der undervisningen skjer. «I skolen» brukes om skolesystemet.',
    topic: 'fast-uttrykk',
    level: 1,
  },
  {
    id: 'uttrykk-hjemme-hos',
    prompt: 'Jeg er hjemme ___ Kari i kveld.',
    answer: 'hos',
    options: ['hos', 'ved', 'på', 'til'],
    explanation: '«Hjemme hos» + person: hjemme hos meg, hjemme hos Kari.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-pa-landet',
    prompt: 'Han bor ___ landet, ikke i byen.',
    answer: 'på',
    options: ['på', 'ved', 'hos', 'til'],
    explanation: 'Fast uttrykk: «på landet» = på bygda. «I landet» betyr i staten, ikke på bygda.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-i-telefonen',
    prompt: 'Snakker du ___ telefonen?',
    answer: 'i',
    options: ['i', 'ved', 'til', 'av'],
    explanation: 'Fast uttrykk: «snakke i telefonen». «På telefonen» høres også, men «i» er normen.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Sprichst du am Telefon?',
  },
  {
    id: 'uttrykk-i-avisa',
    prompt: 'Det står ___ avisa i dag.',
    answer: 'i',
    options: ['i', 'på', 'ved', 'over'],
    explanation: 'Tekstkilder tar «i»: i avisa, i boka, i brevet.',
    topic: 'fast-uttrykk',
    level: 1,
  },
  {
    id: 'uttrykk-ved-bordet',
    prompt: 'Vi sitter ___ bordet og spiser.',
    answer: 'ved',
    options: ['ved', 'på', 'i', 'hos'],
    explanation: 'Fast uttrykk: «sitte ved bordet». «På bordet» ville plassert deg oppå det.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-pa-vei',
    prompt: 'Hun er ___ vei til jobben.',
    answer: 'på',
    options: ['på', 'i', 'under', 'ved'],
    explanation: 'Fast uttrykk: «på vei». Adverbet «underveis» skrives i ett ord.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-pa-nett',
    prompt: 'Jeg kjøpte det ___ nett.',
    answer: 'på',
    options: ['på', 'i', 'til', 'hos'],
    explanation: 'Fast uttrykk: «på nett», «på internett».',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-allergisk-mot',
    prompt: 'Jeg er allergisk ___ nøtter.',
    answer: 'mot',
    options: ['mot', 'av', 'på', 'med'],
    explanation: '«Allergisk mot» noe. Tysk «allergisch gegen».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Ich bin allergisch gegen Nüsse.',
  },
  {
    id: 'uttrykk-snill-mot',
    prompt: 'Hun er alltid snill ___ dyr.',
    answer: 'mot',
    options: ['mot', 'for', 'av', 'til'],
    explanation: '«Snill mot» noen. Samme mønster: grei mot, slem mot.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Sie ist immer lieb zu Tieren.',
  },
  {
    id: 'uttrykk-sint-pa',
    prompt: 'Mamma er sint ___ meg fordi jeg kom for sent.',
    answer: 'på',
    options: ['på', 'til', 'av', 'i'],
    explanation: '«Sint på» noen. Tysk «böse auf».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Mama ist böse auf mich, weil ich zu spät gekommen bin.',
  },
  {
    id: 'uttrykk-sjalu-pa',
    prompt: 'Han er sjalu ___ broren sin.',
    answer: 'på',
    options: ['på', 'av', 'for', 'mot'],
    explanation: '«Sjalu på» noen. Tysk «eifersüchtig auf».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Er ist eifersüchtig auf seinen Bruder.',
  },
  {
    id: 'uttrykk-god-til',
    prompt: 'Hun er god ___ å lage mat.',
    answer: 'til',
    options: ['til', 'i', 'om', 'av'],
    explanation: '«God til å» eller «flink til å» + verb. Med fag: «god i matte».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Sie kann gut kochen.',
  },
  {
    id: 'uttrykk-vant-til',
    prompt: 'Jeg er ikke vant ___ kulda ennå.',
    answer: 'til',
    options: ['til', 'for', 'på', 'av'],
    explanation: '«Vant til» noe = det føles normalt. Tysk «gewöhnt an».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Ich bin die Kälte noch nicht gewöhnt.',
  },
  {
    id: 'uttrykk-opptatt-av',
    prompt: 'Han er veldig opptatt ___ miljøet.',
    answer: 'av',
    options: ['av', 'for', 'på', 'om'],
    explanation: '«Opptatt av» = interessert i og engasjert. «Opptatt med» = har det travelt med.',
    topic: 'fast-uttrykk',
    level: 3,
  },
  {
    id: 'uttrykk-fornoyd-med',
    prompt: 'Jeg er fornøyd ___ resultatet.',
    answer: 'med',
    options: ['med', 'av', 'for', 'på'],
    explanation: '«Fornøyd med» noe. Tysk «zufrieden mit».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Ich bin mit dem Ergebnis zufrieden.',
  },
  {
    id: 'uttrykk-enig-med',
    prompt: 'Jeg er helt enig ___ deg.',
    answer: 'med',
    options: ['med', 'til', 'av', 'på'],
    explanation: '«Enig med» en person, «enig i» en påstand.',
    topic: 'fast-uttrykk',
    level: 1,
    de: 'Ich bin ganz deiner Meinung.',
  },
  {
    id: 'uttrykk-ferdig-med',
    prompt: 'Er du ferdig ___ boka? Da vil jeg låne den.',
    answer: 'med',
    options: ['med', 'av', 'for', 'til'],
    explanation: '«Ferdig med» noe = har gjort det ferdig.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Bist du mit dem Buch fertig?',
  },
  {
    id: 'uttrykk-kjent-for',
    prompt: 'Bergen er kjent ___ mye regn.',
    answer: 'for',
    options: ['for', 'på', 'om', 'til'],
    explanation: '«Kjent for» = berømt på grunn av. «Kjent med» = har kunnskap om.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Bergen ist für viel Regen bekannt.',
  },
  {
    id: 'uttrykk-ansvarlig-for',
    prompt: 'Hvem er ansvarlig ___ dette prosjektet?',
    answer: 'for',
    options: ['for', 'om', 'på', 'til'],
    explanation: '«Ansvarlig for». Tysk «verantwortlich für» stemmer her.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-viktig-for',
    prompt: 'Familien er viktig ___ meg.',
    answer: 'for',
    options: ['for', 'til', 'av', 'på'],
    explanation: '«Viktig for» noen.',
    topic: 'fast-uttrykk',
    level: 1,
  },
  {
    id: 'uttrykk-skuffet-over',
    prompt: 'Treneren var skuffet ___ resultatet.',
    answer: 'over',
    options: ['over', 'om', 'til', 'for'],
    explanation: '«Skuffet over» noe. Samme mønster: overrasket over, glad over.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Der Trainer war vom Ergebnis enttäuscht.',
  },
  {
    id: 'uttrykk-overrasket-over',
    prompt: 'Jeg ble overrasket ___ hvor kaldt det var.',
    answer: 'over',
    options: ['over', 'om', 'for', 'til'],
    explanation: '«Overrasket over» noe. «Overrasket av» brukes også.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Ich war überrascht, wie kalt es war.',
  },
  {
    id: 'uttrykk-avhengig-av',
    prompt: 'Planen er avhengig ___ været.',
    answer: 'av',
    options: ['av', 'på', 'fra', 'om'],
    explanation: '«Avhengig av». Tysk «abhängig von» blir ikke «fra».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Der Plan ist vom Wetter abhängig.',
  },
  {
    id: 'uttrykk-full-av',
    prompt: 'Glasset er fullt ___ vann.',
    answer: 'av',
    options: ['av', 'fra', 'for', 'om'],
    explanation: '«Full av» noe. I talespråk hører man også «full med».',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-grunn-til',
    prompt: 'Det er ingen grunn ___ bekymring.',
    answer: 'til',
    options: ['til', 'av', 'om', 'på'],
    explanation: '«Grunn til» noe = årsak til det. «På grunn av» er et eget uttrykk.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Es gibt keinen Grund zur Sorge.',
  },
  {
    id: 'uttrykk-sans-for',
    prompt: 'Hun har god sans ___ humor.',
    answer: 'for',
    options: ['for', 'av', 'til', 'om'],
    explanation: '«Sans for» noe = evne til å forstå og sette pris på det.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Sie hat viel Sinn für Humor.',
  },
  {
    id: 'uttrykk-interesse-for',
    prompt: 'Han har stor interesse ___ historie.',
    answer: 'for',
    options: ['for', 'på', 'om', 'til'],
    explanation: 'Substantivet tar «for»: interesse for. Adjektivet tar «i»: interessert i.',
    topic: 'fast-uttrykk',
    level: 3,
  },
  {
    id: 'uttrykk-pa-grunn-av',
    prompt: 'Toget er forsinket på grunn ___ snøen.',
    answer: 'av',
    options: ['av', 'for', 'fra', 'om'],
    explanation: 'Fast uttrykk: «på grunn av» + årsak. Tysk «wegen».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Der Zug hat wegen des Schnees Verspätung.',
  },
  {
    id: 'uttrykk-i-stedet-for',
    prompt: 'Jeg drikker te i stedet ___ kaffe.',
    answer: 'for',
    options: ['for', 'av', 'til', 'om'],
    explanation: 'Fast uttrykk: «i stedet for». Tysk «statt».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Ich trinke Tee statt Kaffee.',
  },
  {
    id: 'uttrykk-for-eksempel',
    prompt: 'Mange land, ___ eksempel Sverige, har en konge.',
    answer: 'for',
    options: ['for', 'av', 'med', 'på'],
    explanation: 'Fast uttrykk: «for eksempel», forkortet «f.eks.».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Viele Länder, zum Beispiel Schweden, haben einen König.',
  },
  {
    id: 'uttrykk-i-hvert-fall',
    prompt: 'Jeg kommer ___ hvert fall i morgen, kanskje i dag også.',
    answer: 'i',
    options: ['i', 'på', 'for', 'om'],
    explanation: 'Fast uttrykk: «i hvert fall» = uansett, i alle fall.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Ich komme auf jeden Fall morgen, vielleicht auch heute.',
  },
  {
    id: 'uttrykk-i-ferd-med',
    prompt: 'Hun er ___ ferd med å pakke kofferten.',
    answer: 'i',
    options: ['i', 'på', 'om', 'med'],
    explanation: '«I ferd med å» = holder på med å, akkurat nå.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Sie ist gerade dabei, den Koffer zu packen.',
  },
  {
    id: 'uttrykk-til-tross-for',
    prompt: 'Vi gikk tur ___ tross for regnet.',
    answer: 'til',
    options: ['til', 'på', 'i', 'med'],
    explanation: 'Fast uttrykk: «til tross for». Tysk «trotz».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Wir sind trotz des Regens spazieren gegangen.',
  },
  {
    id: 'uttrykk-til-frokost',
    prompt: 'Hva spiser du ___ frokost?',
    answer: 'til',
    options: ['til', 'for', 'på', 'i'],
    explanation: 'Måltider tar «til»: til frokost, til middag. Tysk «zum Frühstück».',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Was isst du zum Frühstück?',
  },
  {
    id: 'uttrykk-til-slutt',
    prompt: 'Laget vant ___ slutt etter en lang kamp.',
    answer: 'til',
    options: ['til', 'på', 'i', 'om'],
    explanation: 'Fast uttrykk: «til slutt» = til sist. «På slutten» betyr i den siste delen.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Die Mannschaft hat nach einem langen Spiel schließlich gewonnen.',
  },
  {
    id: 'uttrykk-blant-annet',
    prompt: 'Vi besøkte ___ annet Oslo og Bergen.',
    answer: 'blant',
    options: ['blant', 'mellom', 'med', 'over'],
    explanation: 'Fast uttrykk: «blant annet», forkortet «bl.a.».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Wir haben unter anderem Oslo und Bergen besucht.',
  },
  {
    id: 'uttrykk-uten-tvil',
    prompt: 'Det var ___ tvil den beste konserten i år.',
    answer: 'uten',
    options: ['uten', 'av', 'for', 'om'],
    explanation: 'Fast uttrykk: «uten tvil» = helt sikkert.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Das war zweifellos das beste Konzert des Jahres.',
  },
  {
    id: 'uttrykk-sto-uten-penger',
    prompt: 'Jeg sto plutselig ___ penger i en fremmed by.',
    answer: 'uten',
    options: ['uten', 'av', 'for', 'om'],
    explanation: '«Stå uten» noe = ikke ha det lenger.',
    topic: 'fast-uttrykk',
    level: 2,
    de: 'Ich stand plötzlich ohne Geld in einer fremden Stadt.',
  },
  {
    id: 'uttrykk-kaffe-uten',
    prompt: 'Jeg drikker kaffen svart, ___ melk og sukker.',
    answer: 'uten',
    options: ['uten', 'av', 'for', 'om'],
    explanation: 'Svart kaffe har verken melk eller sukker i seg.',
    topic: 'fast-uttrykk',
    level: 1,
  },
  {
    id: 'uttrykk-ved-hjelp-av',
    prompt: 'Vi løste oppgaven ___ hjelp av en kalkulator.',
    answer: 'ved',
    options: ['ved', 'for', 'i', 'til'],
    explanation: 'Fast uttrykk: «ved hjelp av» = med bruk av.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Wir haben die Aufgabe mithilfe eines Taschenrechners gelöst.',
  },
  {
    id: 'uttrykk-under-annet-navn',
    prompt: 'Hun skriver bøker ___ et annet navn.',
    answer: 'under',
    options: ['under', 'av', 'mot', 'til'],
    explanation: '«Under et annet navn» = med et dekknavn. Tysk «unter einem anderen Namen».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Sie schreibt Bücher unter einem anderen Namen.',
  },
  {
    id: 'uttrykk-ligger-foran',
    prompt: 'Norge ligger to poeng ___ Sverige etter første omgang.',
    answer: 'foran',
    options: ['foran', 'mellom', 'gjennom', 'blant'],
    explanation: 'Den som leder i en konkurranse, «ligger foran».',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Norwegen liegt nach der ersten Halbzeit zwei Punkte vor Schweden.',
  },
  {
    id: 'uttrykk-forskjellen-mellom',
    prompt: 'Hva er forskjellen ___ «i» og «på»?',
    answer: 'mellom',
    options: ['mellom', 'blant', 'av', 'gjennom'],
    explanation: '«Forskjellen mellom» to ting. «Forskjellen på» brukes også.',
    topic: 'fast-uttrykk',
    level: 2,
  },
  {
    id: 'uttrykk-om-igjen',
    prompt: 'Det ble feil, så vi må gjøre alt ___ igjen.',
    answer: 'om',
    options: ['om', 'på', 'i', 'for'],
    explanation: '«Om igjen» = en gang til, fra begynnelsen.',
    topic: 'fast-uttrykk',
    level: 3,
    de: 'Es war falsch, also müssen wir alles noch einmal machen.',
  },

  // --- Middel, årsak, tilhørighet ---------------------------------------------
  {
    id: 'middel-med-bussen',
    prompt: 'Jeg drar ___ bussen til byen.',
    answer: 'med',
    options: ['med', 'i', 'ved', 'av'],
    explanation: 'Transportmiddel: «med bussen, med tog, med bil». Er du allerede om bord, sitter du «på bussen».',
    topic: 'middel',
    level: 1,
    de: 'Ich fahre mit dem Bus in die Stadt.',
  },
  {
    id: 'middel-for-hand',
    prompt: 'Han skrev brevet ___ hånd.',
    answer: 'for',
    options: ['for', 'på', 'i', 'av'],
    explanation: 'Fast uttrykk: «for hånd» = ikke på maskin.',
    topic: 'middel',
    level: 3,
    de: 'Er hat den Brief mit der Hand geschrieben.',
  },
  {
    id: 'middel-bygd-av-tre',
    prompt: 'Huset er bygd ___ tre.',
    answer: 'av',
    options: ['av', 'fra', 'til', 'om'],
    explanation: 'Materiale: «av tre, av stein, av glass». Tysk «aus Holz» blir ikke «fra».',
    topic: 'middel',
    level: 2,
    de: 'Das Haus ist aus Holz gebaut.',
  },
  {
    id: 'middel-venn-av-meg',
    prompt: 'Dette er en venn ___ meg.',
    answer: 'av',
    options: ['av', 'fra', 'med', 'om'],
    explanation: 'Én av flere: «en venn av meg», «en kollega av meg».',
    topic: 'middel',
    level: 3,
  },
  {
    id: 'middel-gave-til-deg',
    prompt: 'Gaven er ___ deg.',
    answer: 'til',
    options: ['til', 'av', 'med', 'om'],
    explanation: 'Mottaker: «til». Gaven er til deg, brevet er til mamma.',
    topic: 'middel',
    level: 2,
  },
  {
    id: 'middel-uten-hjelp',
    prompt: 'Vi klarte det helt alene, ___ hjelp fra noen.',
    answer: 'uten',
    options: ['uten', 'med', 'av', 'for'],
    explanation: '«Uten» = mangel på noe: uten hjelp, uten penger. «Helt alene» utelukker «med».',
    topic: 'middel',
    level: 1,
    allowedContrasts: ['med'],
  },
  {
    id: 'middel-kjopte-for-tusen',
    prompt: 'Jeg kjøpte sykkelen ___ tusen kroner.',
    answer: 'for',
    options: ['for', 'av', 'om', 'med'],
    explanation: 'Pris: «kjøpe eller selge noe for tusen kroner».',
    topic: 'middel',
    level: 3,
  },
  {
    id: 'middel-betale-med-kort',
    prompt: 'Kan jeg betale ___ kort?',
    answer: 'med',
    options: ['med', 'av', 'i', 'til'],
    explanation: 'Betalingsmiddel tar «med»: med kort, med kontanter.',
    topic: 'middel',
    level: 1,
    de: 'Kann ich mit Karte bezahlen?',
  },
  {
    id: 'middel-skriv-med-blyant',
    prompt: 'Skriv navnet ditt ___ blyant.',
    answer: 'med',
    options: ['med', 'av', 'på', 'for'],
    explanation: 'Redskap tar «med»: skrive med blyant, spise med gaffel.',
    topic: 'middel',
    level: 1,
    de: 'Schreib deinen Namen mit Bleistift.',
  },
];

/** Catches copy-paste slips while editing; a duplicate id would merge two items' SRS history. */
function assertValidItems(items: readonly CuratedItem[]): void {
  const seenIds = new Set<string>();

  for (const item of items) {
    if (seenIds.has(item.id)) {
      throw new Error(`curated.ts: duplicate id "${item.id}"`);
    }

    seenIds.add(item.id);

    const problems: string[] = [];

    if (item.prompt.split('___').length !== 2) {
      problems.push('prompt needs exactly one ___');
    }

    if (!item.options.includes(item.answer)) {
      problems.push('answer missing from options');
    }

    if (new Set(item.options).size !== item.options.length) {
      problems.push('duplicate option');
    }

    if (problems.length > 0) {
      throw new Error(`curated.ts: item "${item.id}": ${problems.join(', ')}`);
    }
  }
}

if (import.meta.env.DEV) {
  assertValidItems(ITEMS);
}

function exerciseId(item: CuratedItem): string {
  return `p-curated-${item.id}`;
}

export const CURATED_EXERCISES: readonly Exercise[] = ITEMS.map((item) => ({
  kind: 'multiple-choice',
  id: exerciseId(item),
  deckId: 'prepositions',
  prompt: item.prompt,
  solution: item.prompt.replace('___', item.answer),
  explanation: item.explanation,
  answer: item.answer,
  options: item.options,
  level: item.level,
  tags: [item.answer, `tema:${item.topic}`],
  ...(item.de === undefined ? {} : { translations: { de: item.de } }),
}));

/** Exercise id → excluded distractors its context explicitly allows; read by the content test. */
export const CURATED_ALLOWED_CONTRASTS: ReadonlyMap<string, readonly Preposition[]> = new Map(
  ITEMS.flatMap((item) =>
    item.allowedContrasts === undefined ? [] : [[exerciseId(item), item.allowedContrasts] as const],
  ),
);
