/**
 * Preposition deck: two pools of cloze items, each practised as multiple
 * choice or typed in.
 *
 * - `authored.json`: sentences written (with AI) for this app, in template
 *   form. An entry is one sentence, or a pattern with a `{slot}` and fillers
 *   that each keep the rule intact. Every distractor must be clearly wrong in
 *   its sentence: antonyms and near-synonyms that also fit («før/etter jobb»)
 *   belong in `alternatives`, not in `options`. `content.test.ts` enforces
 *   the mechanical part.
 * - `tatoeba.json`: Tatoeba sentences, generated by `pnpm run data`.
 *   `overrides.json` adds reviewed alternatives, AI translations and
 *   exclusions on top, since the generated file is overwritten.
 */
import { expandAuthored, parseAuthored } from '../../core/authored.ts';
import {
  LANGUAGE_CODES,
  type ClozeItem,
  type DataItem,
  type Deck,
  type DeckSource,
  type ExerciseKind,
  type LanguageCode,
  type TranslationCredit,
} from '../../core/types.ts';
import { reviewedTatoebaLoader } from '../tatoeba-source.ts';

const DECK_ID = 'prepositions';

const PRACTICE_TASKS: readonly ExerciseKind[] = ['multiple-choice', 'type-in'];

/** Authored sentences and their translations were written with AI for this app. */
function withOwnSource(item: ClozeItem): ClozeItem {
  const translations: Partial<Record<LanguageCode, TranslationCredit>> = {};

  for (const lang of LANGUAGE_CODES) {
    if (item.translations?.[lang] !== undefined) {
      translations[lang] = { machine: true };
    }
  }

  return { ...item, source: { name: 'KI-generert for Norskinator', id: item.id, translations } };
}

async function loadAuthored(): Promise<ClozeItem[]> {
  const raw: unknown = (await import('./authored.json')).default;

  return expandAuthored(DECK_ID, parseAuthored(raw)).map(withOwnSource);
}

const loadReviewedTatoeba = reviewedTatoebaLoader(
  { deckId: DECK_ID, idPrefix: 'p-' },
  // Dynamic import keeps the ~430 kB corpus out of the initial bundle.
  async () => (await import('./tatoeba.json')).default,
  async () => (await import('./overrides.json')).default,
);

function clozeSource(load: () => Promise<readonly DataItem[]>): DeckSource {
  return { dataKind: 'cloze', tasks: PRACTICE_TASKS, load };
}

export const prepositionDeck: Deck = {
  id: DECK_ID,
  title: 'Preposisjoner',
  shortTitle: 'Preposisjoner',
  description: 'i, på, til, av … Finn riktig preposisjon i setningen.',
  icon: '🧭',
  tagLabel: 'Preposisjon',
  sources: [
    clozeSource(loadAuthored),
    clozeSource(loadReviewedTatoeba),
  ],
};
